### ISSUE TITLE
Did I forget something

### ISSUE THREAD

**Issue by cybe42** [kimbring2/MineRL#4]
Traceback (most recent call last):
  File "/home/cybe/Desktop/gitrepos/minecraft_ai/learner.py", line 25, in <module>
    from parametric_distribution import get_parametric_distribution_for_action_space
ModuleNotFoundError: No module named 'parametric_distribution'

**Comment by kimbring2** [comment]
@cybe42 I forget to upload parametric_distribution.py file. I upload it just now. 
Sorry for inconvenient.
